// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PostEditorController from "./post_editor_controller"
application.register("post-editor", PostEditorController)

import ChatController from "./chat_controller"
application.register("chat", ChatController)

import TelegramBotFormController from "./telegram_bot_form_controller"
application.register("telegram-bot-form", TelegramBotFormController)

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)
