// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import PostEditorController from "./post_editor_controller"
application.register("post-editor", PostEditorController)

import ChatController from "./chat_controller"
application.register("chat", ChatController)

import TelegramBotFormController from "./telegram_bot_form_controller"
application.register("telegram-bot-form", TelegramBotFormController)

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import AnalyticsController from "./analytics_controller"
application.register("analytics", AnalyticsController)

import EditorPanelsController from "./editor_panels_controller"
application.register("editor-panels", EditorPanelsController)

import ImageGeneratorController from "./image_generator_controller"
application.register("image-generator", ImageGeneratorController)

import ArticleGeneratorController from "./article_generator_controller"
application.register("article-generator", ArticleGeneratorController)

import BulkSelectController from "./bulk_select_controller"
application.register("bulk-select", BulkSelectController)

import InfiniteScrollController from "./infinite_scroll_controller"
application.register("infinite-scroll", InfiniteScrollController)

import PostScrollController from "./post_scroll_controller"
application.register("post-scroll", PostScrollController)
